# Generated by Django 5.2.4 on 2025-08-08 10:05

import django.db.models.deletion
import django.utils.timezone
import signage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('total_ram', models.CharField(max_length=50)),
                ('total_storage', models.CharField(max_length=50)),
                ('resolution', models.CharField(default='Unknown', max_length=50)),
                ('is_online', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TestDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField()),
                ('ip_address', models.CharField(max_length=50)),
                ('last_online', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=signage.models.content_file_path)),
                ('supported_device', models.CharField(blank=True, choices=[('S', 'S (640 X 480)'), ('M', 'M (1280 X 720)'), ('L', 'L (1920 X 1080)'), ('XL', 'XL (2560 X 1440)'), ('XXL', 'XXL (3840 X 2160)'), ('XXXL', 'XXXL (> 4K)')], help_text='Auto-set dari resolusi Device terkait', max_length=10)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='signage.device')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='playlist_uploads/')),
                ('supported_device', models.CharField(blank=True, choices=[('S', 'S (640 X 480)'), ('M', 'M (1280 X 720)'), ('L', 'L (1920 X 1080)'), ('XL', 'XL (2560 X 1440)'), ('XXL', 'XXL (3840 X 2160)'), ('XXXL', 'XXXL (> 4K)')], help_text="Auto-set from the associated device's resolution", max_length=10)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='signage.device')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=100)),
                ('schedule_type', models.CharField(choices=[('None', 'None'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('List', 'List')], max_length=20)),
                ('publish_status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=10)),
                ('playback_date', models.DateField(blank=True, null=True)),
                ('never_expire', models.BooleanField(default=False)),
                ('repeat', models.BooleanField(default=False)),
                ('playback_start', models.TimeField(blank=True, null=True)),
                ('playback_end', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signage.content')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signage.playlist')),
                ('publish_to', models.ManyToManyField(blank=True, related_name='published_schedules', to='signage.device')),
                ('publish_to_test_devices', models.ManyToManyField(blank=True, related_name='published_schedules', to='signage.testdevice')),
            ],
        ),
    ]
