# Generated by Django 5.2.4 on 2025-08-10 23:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama grup (Contoh: Ballroom 1, Ivory 2)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Deskripsi tambahan grup', null=True)),
                ('device_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Jumlah Perangkat')),
                ('schedule_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Jumlah Schedule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Group',
                'verbose_name_plural': 'Device Groups',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='publish_to_test_devices',
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['group__name', 'name'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='device',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='device',
            name='total_ram',
        ),
        migrations.RemoveField(
            model_name='device',
            name='total_storage',
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, help_text='Nama perangkat (opsional)', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='user_agent',
            field=models.TextField(default=django.utils.timezone.now, help_text='Identifikasi browser/perangkat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(help_text='Alamat IP perangkat', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Status koneksi perangkat'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Terakhir update status'),
        ),
        migrations.AlterField(
            model_name='device',
            name='resolution',
            field=models.CharField(default='Unknown', help_text='Resolusi layar (format: WxH)', max_length=50),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['publish_status'], name='signage_sch_publish_6db536_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['playback_date'], name='signage_sch_playbac_ff6d53_idx'),
        ),
        migrations.AddIndex(
            model_name='devicegroup',
            index=models.Index(fields=['name'], name='signage_dev_name_efc62b_idx'),
        ),
        migrations.AddIndex(
            model_name='devicegroup',
            index=models.Index(fields=['device_count'], name='signage_dev_device__f5c46e_idx'),
        ),
        migrations.AddIndex(
            model_name='devicegroup',
            index=models.Index(fields=['schedule_count'], name='signage_dev_schedul_7e485a_idx'),
        ),
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Grup tempat perangkat ini berada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='signage.devicegroup'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['ip_address'], name='signage_dev_ip_addr_cbafdb_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_online'], name='signage_dev_is_onli_c48543_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['group'], name='signage_dev_group_i_612424_idx'),
        ),
        migrations.DeleteModel(
            name='TestDevice',
        ),
    ]
