# Generated by Django 5.2.4 on 2025-08-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_devicegroup_remove_schedule_publish_to_test_devices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='supported_device',
            field=models.CharField(blank=True, help_text='Auto-set dari device yang dipilih (Group + Resolution)', max_length=200),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='supported_device',
            field=models.CharField(blank=True, help_text='Auto-set dari device yang dipilih (Group + Resolution)', max_length=200),
        ),
    ]
